---
# --------------------- #
## mysql
mysql_root_password: "{{ MYSQL_ROOT_PASSWORD }}"
mysql_bind_address: '127.0.0.1'

# --------------------- #
## drupal
drupal_core_version: "7.x"

# The path where Drupal will be downloaded and installed.
drupal_core_path: "/var/www/{{ drupal_domain }}"

# Your drupal site's domain name (e.g. 'example.com').
drupal_domain: "medneta.eu"

# Your Drupal site admin account credentials.
drupal_admin_name: "{{ DRUPAL_ADMIN_NAME }}"
drupal_admin_password: "{{ DRUPAL_ADMIN_PASSWORD }}"

# The webserver you're running (e.g. 'apache2', 'httpd', 'nginx').
drupal_webserver_daemon: apache2

# Drupal MySQL database username and password.
drupal_mysql_user: "{{ DRUPAL_MYSQL_USER }}"
drupal_mysql_password: "{{ DRUPAL_MYSQL_PASSWORD }}"
drupal_mysql_database: "{{ DRUPAL_MYSQL_DATABASE }}"

# Whether to use the included vhost file. Set this to `false` if you intend to
# handle vhosts with another role (e.g. geerlingguy.apache).
drupal_include_web_vhost: false

# --------------------- #
## apache
apache_vhosts:
  - servername: "{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
